language: python
python:
 - "3.6"

branches:
  only:
    - master

script: python3 ./manage.py test

deploy:
  provider: surge
  project: .
  domain: victormrmintegracion.surge.sh
  skip_cleanup: true
